version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    container_name: db_advertisement_api
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    expose:
      - 1221
    ports:
      - "${DB_PORT}:1221"
    env_file:
      - .env

  db-test:
    image: postgres:16
    container_name: test_db_advertisement_api
    environment:
      POSTGRES_DB: ${DB_TEST_NAME}
      POSTGRES_USER: ${DB_TEST_USER}
      POSTGRES_PASSWORD: ${DB_TEST_PASS}
    expose:
      - 5432
    ports:
      - "${DB_TEST_PORT}:5432"
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.13.4-management
    restart: always
    container_name: rabbitmq_advertisement_api
    expose:
      - 5672
      - 15672

  app:
    build:
      context: .
    restart: always
    env_file:
      - .env
    container_name: app_advertisement_api
    ports:
      - 8080:8080
    command: ["sh", "./docker/app.sh"]
    volumes:
      - ./migrations/versions:/advertisement_api/migrations/versions
      - ./logs:/advertisement_api/logs
    depends_on:
      - db
      - db-test
      - rabbitmq